version: '3.8'

services:
  app:
    build:
      context: ./
    image: ajurkiewicz/devops-task-app:1.0.0
    working_dir: /app/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

  nginx:
    build: ./services/nginx
    image: ajurkiewicz/devops-task-nginx:1.0.0
    ports:
      - 8080:80
    depends_on:
      - app

volumes:
  postgres_data:
